// Copyright © 2020 Randall Maas. All rights reserved.
// See LICENSE file in the project root for full license information.  
// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Anki.VectorAnim
{

using global::System;
using global::FlatBuffers;

/// <summary>
/// The AudioState structure is used to put the audio system into a particular state.  
/// </summary>
public struct AudioState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AudioState GetRootAsAudioState(ByteBuffer _bb) { return GetRootAsAudioState(_bb, new AudioState()); }
  public static AudioState GetRootAsAudioState(ByteBuffer _bb, AudioState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AudioState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// <summary>
  /// The state group to modify.  Default: 0
  /// </summary>
  public uint StateGroupId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  /// <summary>
  /// The new state to put the group into.  Default: 0
  /// </summary>
  public uint StateId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<AudioState> CreateAudioState(FlatBufferBuilder builder,
      uint stateGroupId = 0,
      uint stateId = 0) {
    builder.StartObject(2);
    AudioState.AddStateId(builder, stateId);
    AudioState.AddStateGroupId(builder, stateGroupId);
    return AudioState.EndAudioState(builder);
  }

  public static void StartAudioState(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddStateGroupId(FlatBufferBuilder builder, uint stateGroupId) { builder.AddUint(0, stateGroupId, 0); }
  public static void AddStateId(FlatBufferBuilder builder, uint stateId) { builder.AddUint(1, stateId, 0); }
  public static Offset<AudioState> EndAudioState(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AudioState>(o);
  }
};


}
