// Copyright © 2020 Randall Maas. All rights reserved.
// See LICENSE file in the project root for full license information.  
// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Anki.VectorAnim
{
    using Anki.CozmoAnim;
using global::System;
using global::FlatBuffers;

/// <summary>
/// The KeyFrames structure provides separate time-coded key frames for each of
/// the possible tracks in the animation.  The tracks are optional.  There
/// tracks may have different numbers of key frames.  The key frames do not
///  need to start at the same time(s).   
/// </summary>
public struct Keyframes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Keyframes GetRootAsKeyframes(ByteBuffer _bb) { return GetRootAsKeyframes(_bb, new Keyframes()); }
  public static Keyframes GetRootAsKeyframes(ByteBuffer _bb, Keyframes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Keyframes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// <summary>
  /// A series of key frames describing when and how the lift should move.
  /// </summary>
  public LiftHeight? LiftHeightKeyFrame(int j) { int o = __p.__offset(4); return o != 0 ? (LiftHeight?)(new LiftHeight()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LiftHeightKeyFrameLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames describing when and how the eyes should move.
  /// </summary>
  public ProceduralFace? ProceduralFaceKeyFrame(int j) { int o = __p.__offset(6); return o != 0 ? (ProceduralFace?)(new ProceduralFace()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ProceduralFaceKeyFrameLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames describing when and how the head should move.
  /// </summary>
  public HeadAngle? HeadAngleKeyFrame(int j) { int o = __p.__offset(8); return o != 0 ? (HeadAngle?)(new HeadAngle()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HeadAngleKeyFrameLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  ///A series of key frames describing when and how audio should be played.
  /// </summary>
  public RobotAudio? RobotAudioKeyFrame(int j) { int o = __p.__offset(10); return o != 0 ? (RobotAudio?)(new RobotAudio()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RobotAudioKeyFrameLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// A series of key frames describing when and how the backpack lights should
  /// be illuminated.
  public BackpackLights? BackpackLightsKeyFrame(int j) { int o = __p.__offset(12); return o != 0 ? (BackpackLights?)(new BackpackLights()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BackpackLightsKeyFrameLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames describing when and how the face should move.
  /// </summary>
  public FaceAnimation? FaceAnimationKeyFrame(int j) { int o = __p.__offset(14); return o != 0 ? (FaceAnimation?)(new FaceAnimation()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FaceAnimationKeyFrameLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// Note: many behaviors do not support event key frames; those that do expect
  /// a specific event, and number of event key frames.
  /// </summary>
  public Event? EventKeyFrame(int j) { int o = __p.__offset(16); return o != 0 ? (Event?)(new Event()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EventKeyFrameLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames to drive and turn the body.
  /// </summary>
  public BodyMotion? BodyMotionKeyFrame(int j) { int o = __p.__offset(18); return o != 0 ? (BodyMotion?)(new BodyMotion()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BodyMotionKeyFrameLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames to record the current heading of the robot so that
  /// the animation can return to them later.
  /// </summary>
  public RecordHeading? RecordHeadingKeyFrame(int j) { int o = __p.__offset(20); return o != 0 ? (RecordHeading?)(new RecordHeading()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RecordHeadingKeyFrameLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames used to return the robot so a previously saved
  /// heading after a movement.
  /// </summary>
  public TurnToRecordedHeading? TurnToRecordedHeadingKeyFrame(int j) { int o = __p.__offset(22); return o != 0 ? (TurnToRecordedHeading?)(new TurnToRecordedHeading()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TurnToRecordedHeadingKeyFrameLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// <summary>
  /// A series of key frames for the visual sprite box animation.  New in version 1.7.
  /// </summary>
  public SpriteBox? SpriteBoxKeyFrame(int j) { int o = __p.__offset(24); return o != 0 ? (SpriteBox?)(new SpriteBox()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SpriteBoxKeyFrameLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Keyframes> CreateKeyframes(FlatBufferBuilder builder,
      VectorOffset LiftHeightKeyFrameOffset = default(VectorOffset),
      VectorOffset ProceduralFaceKeyFrameOffset = default(VectorOffset),
      VectorOffset HeadAngleKeyFrameOffset = default(VectorOffset),
      VectorOffset RobotAudioKeyFrameOffset = default(VectorOffset),
      VectorOffset BackpackLightsKeyFrameOffset = default(VectorOffset),
      VectorOffset FaceAnimationKeyFrameOffset = default(VectorOffset),
      VectorOffset EventKeyFrameOffset = default(VectorOffset),
      VectorOffset BodyMotionKeyFrameOffset = default(VectorOffset),
      VectorOffset RecordHeadingKeyFrameOffset = default(VectorOffset),
      VectorOffset TurnToRecordedHeadingKeyFrameOffset = default(VectorOffset),
      VectorOffset SpriteBoxKeyFrameOffset = default(VectorOffset)) {
    builder.StartObject(11);
    Keyframes.AddSpriteBoxKeyFrame(builder, SpriteBoxKeyFrameOffset);
    Keyframes.AddTurnToRecordedHeadingKeyFrame(builder, TurnToRecordedHeadingKeyFrameOffset);
    Keyframes.AddRecordHeadingKeyFrame(builder, RecordHeadingKeyFrameOffset);
    Keyframes.AddBodyMotionKeyFrame(builder, BodyMotionKeyFrameOffset);
    Keyframes.AddEventKeyFrame(builder, EventKeyFrameOffset);
    Keyframes.AddFaceAnimationKeyFrame(builder, FaceAnimationKeyFrameOffset);
    Keyframes.AddBackpackLightsKeyFrame(builder, BackpackLightsKeyFrameOffset);
    Keyframes.AddRobotAudioKeyFrame(builder, RobotAudioKeyFrameOffset);
    Keyframes.AddHeadAngleKeyFrame(builder, HeadAngleKeyFrameOffset);
    Keyframes.AddProceduralFaceKeyFrame(builder, ProceduralFaceKeyFrameOffset);
    Keyframes.AddLiftHeightKeyFrame(builder, LiftHeightKeyFrameOffset);
    return Keyframes.EndKeyframes(builder);
  }

  public static void StartKeyframes(FlatBufferBuilder builder) { builder.StartObject(11); }
  public static void AddLiftHeightKeyFrame(FlatBufferBuilder builder, VectorOffset LiftHeightKeyFrameOffset) { builder.AddOffset(0, LiftHeightKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateLiftHeightKeyFrameVector(FlatBufferBuilder builder, Offset<LiftHeight>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLiftHeightKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<LiftHeight>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartLiftHeightKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddProceduralFaceKeyFrame(FlatBufferBuilder builder, VectorOffset ProceduralFaceKeyFrameOffset) { builder.AddOffset(1, ProceduralFaceKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateProceduralFaceKeyFrameVector(FlatBufferBuilder builder, Offset<ProceduralFace>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateProceduralFaceKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<ProceduralFace>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartProceduralFaceKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHeadAngleKeyFrame(FlatBufferBuilder builder, VectorOffset HeadAngleKeyFrameOffset) { builder.AddOffset(2, HeadAngleKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateHeadAngleKeyFrameVector(FlatBufferBuilder builder, Offset<HeadAngle>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHeadAngleKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<HeadAngle>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartHeadAngleKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRobotAudioKeyFrame(FlatBufferBuilder builder, VectorOffset RobotAudioKeyFrameOffset) { builder.AddOffset(3, RobotAudioKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateRobotAudioKeyFrameVector(FlatBufferBuilder builder, Offset<RobotAudio>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRobotAudioKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<RobotAudio>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRobotAudioKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBackpackLightsKeyFrame(FlatBufferBuilder builder, VectorOffset BackpackLightsKeyFrameOffset) { builder.AddOffset(4, BackpackLightsKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateBackpackLightsKeyFrameVector(FlatBufferBuilder builder, Offset<BackpackLights>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBackpackLightsKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<BackpackLights>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartBackpackLightsKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFaceAnimationKeyFrame(FlatBufferBuilder builder, VectorOffset FaceAnimationKeyFrameOffset) { builder.AddOffset(5, FaceAnimationKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateFaceAnimationKeyFrameVector(FlatBufferBuilder builder, Offset<FaceAnimation>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFaceAnimationKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<FaceAnimation>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartFaceAnimationKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEventKeyFrame(FlatBufferBuilder builder, VectorOffset EventKeyFrameOffset) { builder.AddOffset(6, EventKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateEventKeyFrameVector(FlatBufferBuilder builder, Offset<Event>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEventKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<Event>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartEventKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBodyMotionKeyFrame(FlatBufferBuilder builder, VectorOffset BodyMotionKeyFrameOffset) { builder.AddOffset(7, BodyMotionKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateBodyMotionKeyFrameVector(FlatBufferBuilder builder, Offset<BodyMotion>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBodyMotionKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<BodyMotion>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartBodyMotionKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRecordHeadingKeyFrame(FlatBufferBuilder builder, VectorOffset RecordHeadingKeyFrameOffset) { builder.AddOffset(8, RecordHeadingKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateRecordHeadingKeyFrameVector(FlatBufferBuilder builder, Offset<RecordHeading>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRecordHeadingKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<RecordHeading>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRecordHeadingKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddTurnToRecordedHeadingKeyFrame(FlatBufferBuilder builder, VectorOffset TurnToRecordedHeadingKeyFrameOffset) { builder.AddOffset(9, TurnToRecordedHeadingKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateTurnToRecordedHeadingKeyFrameVector(FlatBufferBuilder builder, Offset<TurnToRecordedHeading>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTurnToRecordedHeadingKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<TurnToRecordedHeading>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTurnToRecordedHeadingKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSpriteBoxKeyFrame(FlatBufferBuilder builder, VectorOffset SpriteBoxKeyFrameOffset) { builder.AddOffset(10, SpriteBoxKeyFrameOffset.Value, 0); }
  public static VectorOffset CreateSpriteBoxKeyFrameVector(FlatBufferBuilder builder, Offset<SpriteBox>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSpriteBoxKeyFrameVectorBlock(FlatBufferBuilder builder, Offset<SpriteBox>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSpriteBoxKeyFrameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Keyframes> EndKeyframes(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Keyframes>(o);
  }
};


}
