//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anki.Resources.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anki.Resources.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interacting with Alexa.
        /// </summary>
        internal static string AlexaInteractionActive {
            get {
                return ResourceManager.GetString("AlexaInteractionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // The paths to search thru (in order) for the independent sprites
        ///  &quot;independentSpritesSearchPaths&quot;: [
        ///    &quot;assets/sprites/independentSprites&quot;,
        ///    &quot;config/sprites/independentSprites&quot;,
        ///    &quot;config/facePNGs&quot;,
        ///    &quot;config/devOnlySprites/independentSprites&quot;
        ///  ],
        ///
        ///  // The paths to search thru (in order) for the sprite sequences
        ///  &quot;spriteSequencesSearchPaths&quot;: [
        ///    &quot;assets/sprites/spriteSequences&quot;,
        ///    // This is in Cozmo, but not Vector
        ///    &quot;assets/faceAnimations&quot;,
        ///    // This is in 1.7, no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string assets_json {
            get {
                return ResourceManager.GetString("assets.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play__Dev_Device__External_Source
        ///Play__Dev_Device__Tone_Generator
        ///Play__Dev_Robot_Factory__Scan_Loop_Stop_Bell
        ///Play__Dev_Robot_Factory__Tone_1K_1Sec
        ///Play__Dev_Robot_Factory__Tone_1K_5Sec
        ///Play__Dev_Robot__Angry_Muttering
        ///Play__Dev_Robot__Curious_Muttering
        ///Play__Dev_Robot__External_Source
        ///Play__Dev_Robot__Freq_Sweep_20Sec
        ///Play__Dev_Robot__Freq_Sweep_5Sec
        ///Play__Dev_Robot__Fx_Test_Sequence
        ///Play__Dev_Robot__Fx_Test_Sequence_Loop_Play
        ///Play__Dev_Robot__Mozart
        ///Play__Dev_Robot__Pink_1Sec
        ///Play__Dev_Rob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audioEvents {
            get {
                return ResourceManager.GetString("audioEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} battery.
        /// </summary>
        internal static string BatteryLevel {
            get {
                return ResourceManager.GetString("BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beat has been detected.
        /// </summary>
        internal static string BeatDetected {
            get {
                return ResourceManager.GetString("BeatDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carrying a cube.
        /// </summary>
        internal static string CarryingCube {
            get {
                return ResourceManager.GetString("CarryingCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detected a cliff.
        /// </summary>
        internal static string CliffDetected {
            get {
                return ResourceManager.GetString("CliffDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // The keys that refer to conditions
        ///  &quot;conditionKeys&quot;: [ &quot;not&quot;, &quot;subCondition&quot;, &quot;and&quot;, &quot;or&quot; ],
        ///  // This maps a type to the keys that are acceptable
        ///  &quot;type2keys&quot;: {
        ///    &quot;AlexaInteractionActive&quot;: [ &quot;conditionType&quot; ],
        ///    &quot;BatteryLevel&quot;: [ &quot;conditionType&quot;, &quot;targetBatteryLevel&quot; ],
        ///    &quot;BeatDetected&quot;: [ &quot;conditionType&quot;, &quot;allowPotentialBeat&quot; ],
        ///    &quot;BehaviorTimer&quot;: [ &quot;conditionType&quot;, &quot;cooldown_s&quot;, &quot;timerName&quot; ],
        ///    &quot;BeingHeld&quot;: [ &quot;conditionType&quot;, &quot;shouldBeHeld&quot; ],
        ///    &quot;CarryingCube&quot;: [ &quot;conditio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string condition_json {
            get {
                return ResourceManager.GetString("condition.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eye contact.
        /// </summary>
        internal static string EyeContact {
            get {
                return ResourceManager.GetString("EyeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falling.
        /// </summary>
        internal static string Falling {
            get {
                return ResourceManager.GetString("Falling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high temperature.
        /// </summary>
        internal static string HighTemperature {
            get {
                return ResourceManager.GetString("HighTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the air.
        /// </summary>
        internal static string InAir {
            get {
                return ResourceManager.GetString("InAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calm.
        /// </summary>
        internal static string InCalmMode {
            get {
                return ResourceManager.GetString("InCalmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance reboot.
        /// </summary>
        internal static string IsMaintenanceReboot {
            get {
                return ResourceManager.GetString("IsMaintenanceReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night time.
        /// </summary>
        internal static string IsNightTime {
            get {
                return ResourceManager.GetString("IsNightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motion detected.
        /// </summary>
        internal static string MotionDetected {
            get {
                return ResourceManager.GetString("MotionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object initally detected.
        /// </summary>
        internal static string ObjectInitialDetection {
            get {
                return ResourceManager.GetString("ObjectInitialDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object known.
        /// </summary>
        internal static string ObjectKnown {
            get {
                return ResourceManager.GetString("ObjectKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obstacle detected.
        /// </summary>
        internal static string ObstacleDetected {
            get {
                return ResourceManager.GetString("ObstacleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off treads.
        /// </summary>
        internal static string OffTreads {
            get {
                return ResourceManager.GetString("OffTreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on his back.
        /// </summary>
        internal static string OnBack {
            get {
                return ResourceManager.GetString("OnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on charger.
        /// </summary>
        internal static string OnCharger {
            get {
                return ResourceManager.GetString("OnCharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on charger platform.
        /// </summary>
        internal static string OnChargerPlatform {
            get {
                return ResourceManager.GetString("OnChargerPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on his face.
        /// </summary>
        internal static string OnFace {
            get {
                return ResourceManager.GetString("OnFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on left side.
        /// </summary>
        internal static string OnLeftSide {
            get {
                return ResourceManager.GetString("OnLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on ride side.
        /// </summary>
        internal static string OnRightSide {
            get {
                return ResourceManager.GetString("OnRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on treads.
        /// </summary>
        internal static string OnTreads {
            get {
                return ResourceManager.GetString("OnTreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in range.
        /// </summary>
        internal static string ProxInRange {
            get {
                return ResourceManager.GetString("ProxInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in habitat.
        /// </summary>
        internal static string RobotInHabitat {
            get {
                return ResourceManager.GetString("RobotInHabitat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picked up.
        /// </summary>
        internal static string RobotPickedUp {
            get {
                return ResourceManager.GetString("RobotPickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pitch.
        /// </summary>
        internal static string RobotPitchInRange {
            get {
                return ResourceManager.GetString("RobotPitchInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on a slope.
        /// </summary>
        internal static string RobotPlacedOnSlope {
            get {
                return ResourceManager.GetString("RobotPlacedOnSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roll in range.
        /// </summary>
        internal static string RobotRollInRange {
            get {
                return ResourceManager.GetString("RobotRollInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shaken.
        /// </summary>
        internal static string RobotShaken {
            get {
                return ResourceManager.GetString("RobotShaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to touched.
        /// </summary>
        internal static string RobotTouched {
            get {
                return ResourceManager.GetString("RobotTouched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salient point detected.
        /// </summary>
        internal static string SalientPointDetected {
            get {
                return ResourceManager.GetString("SalientPointDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stuck on edge.
        /// </summary>
        internal static string StuckOnEdge {
            get {
                return ResourceManager.GetString("StuckOnEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer dedup?.
        /// </summary>
        internal static string TimedDedup {
            get {
                return ResourceManager.GetString("TimedDedup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer in range.
        /// </summary>
        internal static string TimerInRange {
            get {
                return ResourceManager.GetString("TimerInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too hot to charge.
        /// </summary>
        internal static string TooHotToCharge {
            get {
                return ResourceManager.GetString("TooHotToCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heard trigger word.
        /// </summary>
        internal static string TriggerWordPending {
            get {
                return ResourceManager.GetString("TriggerWordPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected movement.
        /// </summary>
        internal static string UnexpectedMovement {
            get {
                return ResourceManager.GetString("UnexpectedMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cube is being held.
        /// </summary>
        internal static string UserIsHoldingCube {
            get {
                return ResourceManager.GetString("UserIsHoldingCube", resourceCulture);
            }
        }
    }
}
