// Copyright © 2020 Randall Maas. All rights reserved.
// See LICENSE file in the project root for full license information.  

using System.Collections.Generic;

namespace Anki.Resources.SDK
{
/// <summary>
/// The behavior to support the Black Jack game
/// </summary>
public partial class BlackJack : BehaviorCoordinator
{
    /// <summary>
    /// 
    /// </summary>
    internal BlackJack() : base(new List<string>()
        {
        "charlieframe",
        "blackjack_player_spadeace",
        "blackjack_player_spade2",
        "blackjack_player_spade3",
        "blackjack_player_spade4",
        "blackjack_player_spade5",
        "blackjack_player_spade6",
        "blackjack_player_spade7",
        "blackjack_player_spade8",
        "blackjack_player_spade9",
        "blackjack_player_spade10",
        "blackjack_player_spadejack",
        "blackjack_player_spadequeen",
        "blackjack_player_spadeking",
        "blackjack_player_heartace",
        "blackjack_player_heart2",
        "blackjack_player_heart3",
        "blackjack_player_heart4",
        "blackjack_player_heart5",
        "blackjack_player_heart6",
        "blackjack_player_heart7",
        "blackjack_player_heart8",
        "blackjack_player_heart9",
        "blackjack_player_heart10",
        "blackjack_player_heartjack",
        "blackjack_player_heartqueen",
        "blackjack_player_heartking",
        "blackjack_player_diamondace",
        "blackjack_player_diamond2",
        "blackjack_player_diamond3",
        "blackjack_player_diamond4",
        "blackjack_player_diamond5",
        "blackjack_player_diamond6",
        "blackjack_player_diamond7",
        "blackjack_player_diamond8",
        "blackjack_player_diamond9",
        "blackjack_player_diamond10",
        "blackjack_player_diamondjack",
        "blackjack_player_diamondqueen",
        "blackjack_player_diamondking",
        "blackjack_player_clubsace",
        "blackjack_player_clubs2",
        "blackjack_player_clubs3",
        "blackjack_player_clubs4",
        "blackjack_player_clubs5",
        "blackjack_player_clubs6",
        "blackjack_player_clubs7",
        "blackjack_player_clubs8",
        "blackjack_player_clubs9",
        "blackjack_player_clubs10",
        "blackjack_player_clubsjack",
        "blackjack_player_clubsqueen",
        "blackjack_player_clubsking",
        "blackjack_vector_card_back",
        "blackjack_vector_spadeace",
        "blackjack_vector_spade2",
        "blackjack_vector_spade3",
        "blackjack_vector_spade4",
        "blackjack_vector_spade5",
        "blackjack_vector_spade6",
        "blackjack_vector_spade7",
        "blackjack_vector_spade8",
        "blackjack_vector_spade9",
        "blackjack_vector_spade10",
        "blackjack_vector_spadejack",
        "blackjack_vector_spadequeen",
        "blackjack_vector_spadeking",
        "blackjack_vector_heartace",
        "blackjack_vector_heart2",
        "blackjack_vector_heart3",
        "blackjack_vector_heart4",
        "blackjack_vector_heart5",
        "blackjack_vector_heart6",
        "blackjack_vector_heart7",
        "blackjack_vector_heart8",
        "blackjack_vector_heart9",
        "blackjack_vector_heart10",
        "blackjack_vector_heartjack",
        "blackjack_vector_heartqueen",
        "blackjack_vector_heartking",
        "blackjack_vector_diamondace",
        "blackjack_vector_diamond2",
        "blackjack_vector_diamond3",
        "blackjack_vector_diamond4",
        "blackjack_vector_diamond5",
        "blackjack_vector_diamond6",
        "blackjack_vector_diamond7",
        "blackjack_vector_diamond8",
        "blackjack_vector_diamond9",
        "blackjack_vector_diamond10",
        "blackjack_vector_diamondjack",
        "blackjack_vector_diamondqueen",
        "blackjack_vector_diamondking",
        "blackjack_vector_clubsace",
        "blackjack_vector_clubs2",
        "blackjack_vector_clubs3",
        "blackjack_vector_clubs4",
        "blackjack_vector_clubs5",
        "blackjack_vector_clubs6",
        "blackjack_vector_clubs7",
        "blackjack_vector_clubs8",
        "blackjack_vector_clubs9",
        "blackjack_vector_clubs10",
        "blackjack_vector_clubsjack",
        "blackjack_vector_clubsqueen",
        "blackjack_vector_clubsking",
        "blackjack_player_back",
        "blackjack_vector_back",
        "blackjack_vector_flipover"},
        new List<string>()
        {"PlayerCardLayout","DealerCardLayout" })
    {
    }
}
}
